name: NeuroLattice CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest -q --disable-warnings --maxfail=1

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 neuro_lattice --max-line-length=120 --ignore=E203,W503
